<a href="https://colab.research.google.com/github/elanghairilanam/Portfolio-Data-Science/blob/main/Analisis_Lingkungan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dt_ISPU = pd.read_excel('ISPU.xlsx')
dt_ISPU

,parameter_pencemar_kritis,kategori,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max
0,NaN,SEDANG,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0
1,NaN,SEDANG,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0
2,PM25,SEDANG,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0
3,PM25,SEDANG,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0
4,PM25,SEDANG,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,PM25,SEDANG,202505,5,27,DKI5 Kebon Jeruk,16.0,59.0,20.0,5.0,22.0,25.0,59.0
2581,PM25,SEDANG,202505,5,28,DKI5 Kebon Jeruk,24.0,100.0,26.0,12.0,29.0,34.0,100.0
2582,PM25,TIDAK SEHAT,202505,5,29,DKI5 Kebon Jeruk,26.0,105.0,26.0,10.0,57.0,53.0,105.0
2583,PM25,SEDANG,202505,5,30,DKI5 Kebon Jeruk,54.0,76.0,21.0,9.0,37.0,54.0,76.0
2584,PM25,TIDAK SEHAT,202505,5,31,DKI5 Kebon Jeruk,35.0,113.0,22.0,13.0,42.0,47.0,113.0

In [9]:
dt_ISPU.describe()

,periode_data,bulan,tanggal,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max
count,2585.000000,2585.000000,2585.000000,2443.000000,2542.000000,2537.000000,2546.000000,2549.000000,2525.000000,2580.000000
mean,202434.698259,5.491296,15.717602,48.607450,68.760425,36.078045,15.515711,24.340133,25.577030,71.016667
std,43.990943,3.400285,8.795797,16.740254,23.309757,17.437682,7.288333,14.063465,16.689747,21.212146
min,202401.000000,1.000000,1.000000,5.000000,10.000000,3.000000,2.000000,2.000000,1.000000,0.000000
25%,202405.000000,3.000000,8.000000,36.000000,54.000000,21.000000,10.000000,14.000000,13.000000,56.000000
50%,202409.000000,5.000000,16.000000,51.000000,70.000000,32.000000,14.000000,21.000000,22.000000,70.000000
75%,202501.000000,8.000000,23.000000,60.000000,85.000000,54.000000,21.000000,31.000000,35.000000,85.000000
max,202505.000000,12.000000,31.000000,187.000000,157.000000,112.000000,70.000000,115.000000,202.000000,202.000000

/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()
/tmp/ipython-input-1207410075.py:4: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_col = row[pollutant_cols].idxmax()

,parameter_pencemar_kritis,kategori,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max
0,nitrogen_dioksida,SEDANG,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0
1,nitrogen_dioksida,SEDANG,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0
2,PM25,SEDANG,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0
3,PM25,SEDANG,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0
4,PM25,SEDANG,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,PM25,SEDANG,202505,5,27,DKI5 Kebon Jeruk,16.0,59.0,20.0,5.0,22.0,25.0,59.0
2581,PM25,SEDANG,202505,5,28,DKI5 Kebon Jeruk,24.0,100.0,26.0,12.0,29.0,34.0,100.0
2582,PM25,TIDAK SEHAT,202505,5,29,DKI5 Kebon Jeruk,26.0,105.0,26.0,10.0,57.0,53.0,105.0
2583,PM25,SEDANG,202505,5,30,DKI5 Kebon Jeruk,54.0,76.0,21.0,9.0,37.0,54.0,76.0
2584,PM25,TIDAK SEHAT,202505,5,31,DKI5 Kebon Jeruk,35.0,113.0,22.0,13.0,42.0,47.0,113.0

In [13]:
dt_ISPU.isna().sum()

parameter_pencemar_kritis     15
kategori                       0
periode_data                   0
bulan                          0
tanggal                        0
stasiun                        0
pm_sepuluh                   142
pm_duakomalima                43
sulfur_dioksida               48
karbon_monoksida              39
ozon                          36
nitrogen_dioksida             60
max                            5
dtype: int64

In [14]:
display(dt_ISPU[dt_ISPU.isnull().any(axis=1)])

,parameter_pencemar_kritis,kategori,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max
2,PM25,SEDANG,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0
72,SO2,SEDANG,202404,4,12,DKI2 Kelapa Gading,27.0,46.0,54.0,5.0,28.0,NaN,54.0
112,SO2,TIDAK SEHAT,202401,1,4,DKI1 Bundaran Hotel Indonesia (HI),30.0,NaN,112.0,20.0,8.0,77.0,112.0
127,SO2,BAIK,202401,1,19,DKI1 Bundaran Hotel Indonesia (HI),19.0,31.0,46.0,NaN,12.0,20.0,46.0
128,SO2,BAIK,202401,1,20,DKI1 Bundaran Hotel Indonesia (HI),26.0,28.0,44.0,NaN,17.0,17.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2563,NaN,TIDAK ADA DATA,202505,5,10,DKI5 Kebon Jeruk,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2564,NO2,BAIK,202505,5,11,DKI5 Kebon Jeruk,37.0,NaN,19.0,21.0,38.0,45.0,45.0
2565,O3,BAIK,202505,5,12,DKI5 Kebon Jeruk,19.0,NaN,19.0,11.0,28.0,27.0,28.0
2566,NO2,BAIK,202505,5,13,DKI5 Kebon Jeruk,19.0,NaN,21.0,5.0,22.0,23.0,23.0
2567,PM25,SEDANG,202505,5,14,DKI5 Kebon Jeruk,NaN,85.0,21.0,12.0,47.0,52.0,85.0

In [15]:
dt_ISPU.dropna(subset=['max'], inplace=True)
display(dt_ISPU.isnull().sum())

parameter_pencemar_kritis     10
kategori                       0
periode_data                   0
bulan                          0
tanggal                        0
stasiun                        0
pm_sepuluh                   137
pm_duakomalima                38
sulfur_dioksida               43
karbon_monoksida              34
ozon                          31
nitrogen_dioksida             55
max                            0
dtype: int64

# Task
Rename all columns in the 'stasiun' column using fuzzy matching to group similar station names, for example, "Bunderan HI" and "Bundaran Hotel Indonesia" should be renamed to "Bundaran HI".

## Install necessary library

### Subtask:
Install a library for fuzzy string matching, such as `fuzzywuzzy`.

**Reasoning**:
The subtask is to install the `fuzzywuzzy` library. This can be done using pip in a separate cell.

In [16]:
%pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

**Reasoning**:
Now that `fuzzywuzzy` is installed, import the necessary modules for the next steps of the original task.

In [17]:
from fuzzywuzzy import process

/usr/local/lib/python3.11/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

## Identify unique station names

### Subtask:
Get the unique values from the 'stasiun' column of the `dt_ISPU` DataFrame.

**Reasoning**:
Access the 'stasiun' column and get the unique values using the `.unique()` method.

In [18]:
unique_stations = dt_ISPU['stasiun'].unique()
display(unique_stations)

array(['DKI3  Jagakarsa', 'DKI1  Bunderan HI', 'DKI2 Kelapa Gading',
       'DKI3 Jagakarsa', 'DKI4 Lubang Buaya', 'DKI2  Kelapa Gading',
       'DKI1  Bundaran Hotel Indonesia (HI)', 'DKI4  Lubang Buaya',
       'DKI5  Kebon Jeruk  Jakarta Barat', 'DKI5 Kebon Jeruk',
       'DKI1 Bundaran Hotel Indonesia (HI)',
       'DKI5 Kebon Jeruk Jakarta Barat'], dtype=object)

## Group similar names

### Subtask:
Implement a fuzzy matching algorithm to group similar station names based on a similarity threshold.

**Reasoning**:
Implement the fuzzy matching algorithm to group similar station names based on a similarity threshold and display the result.

In [19]:
def group_similar_names(names, threshold):
    grouped_names = {}
    for name in names:
        found_match = False
        for grouped_name in grouped_names.keys():
            similarity = process.extractOne(name, [grouped_name])[1]
            if similarity >= threshold:
                grouped_names[grouped_name].append(name)
                found_match = True
                break
        if not found_match:
            grouped_names[name] = [name]
    return grouped_names

grouped_stations = group_similar_names(unique_stations, 85) # Using a threshold of 85
display(grouped_stations)

{'DKI3  Jagakarsa': ['DKI3  Jagakarsa', 'DKI3 Jagakarsa'],
 'DKI1  Bunderan HI': ['DKI1  Bunderan HI',
  'DKI1  Bundaran Hotel Indonesia (HI)',
  'DKI1 Bundaran Hotel Indonesia (HI)'],
 'DKI2 Kelapa Gading': ['DKI2 Kelapa Gading', 'DKI2  Kelapa Gading'],
 'DKI4 Lubang Buaya': ['DKI4 Lubang Buaya', 'DKI4  Lubang Buaya'],
 'DKI5  Kebon Jeruk  Jakarta Barat': ['DKI5  Kebon Jeruk  Jakarta Barat',
  'DKI5 Kebon Jeruk',
  'DKI5 Kebon Jeruk Jakarta Barat']}

## Standardize names

### Subtask:
Replace the original station names in the 'stasiun' column with the chosen standardized name for each group.

**Reasoning**:
Iterate through the grouped_stations dictionary, create a mapping, and replace the station names in the DataFrame.

In [20]:
station_mapping = {}
for standardized_name, original_names in grouped_stations.items():
    for original_name in original_names:
        station_mapping[original_name] = standardized_name

dt_ISPU['stasiun'] = dt_ISPU['stasiun'].replace(station_mapping)
display(dt_ISPU['stasiun'].unique())

array(['DKI3  Jagakarsa', 'DKI1  Bunderan HI', 'DKI2 Kelapa Gading',
       'DKI4 Lubang Buaya', 'DKI5  Kebon Jeruk  Jakarta Barat'],
      dtype=object)

## Verify changes

### Subtask:
Display the unique values in the 'stasiun' column to confirm the standardization.

**Reasoning**:
Display the unique values in the 'stasiun' column to confirm the standardization as per the instructions.

In [21]:
display(dt_ISPU['stasiun'].unique())

array(['DKI3  Jagakarsa', 'DKI1  Bunderan HI', 'DKI2 Kelapa Gading',
       'DKI4 Lubang Buaya', 'DKI5  Kebon Jeruk  Jakarta Barat'],
      dtype=object)

## Summary:

### Data Analysis Key Findings

*   The `fuzzywuzzy` library was successfully installed and used for fuzzy string matching.
*   Unique station names were extracted from the 'stasiun' column.
*   Similar station names were grouped together based on a similarity threshold of 85 using fuzzy matching. For example, 'DKI1 Bunderan HI' and 'DKI1 Bundaran Hotel Indonesia (HI)' were grouped under 'DKI1 Bunderan HI'.
*   The original station names in the 'stasiun' column were replaced with their corresponding standardized names.
*   The unique values in the 'stasiun' column after standardization are 'DKI3 Jagakarsa', 'DKI1 Bunderan HI', 'DKI2 Kelapa Gading', 'DKI4 Lubang Buaya', and 'DKI5 Kebon Jeruk Jakarta Barat'.

### Insights or Next Steps

*   Consider optimizing the fuzzy matching process by installing `python-Levenshtein` as suggested by the warning message for potentially better performance.
*   Review the standardized station names to ensure they are accurate and representative of the original groups. Adjust the fuzzy matching threshold if necessary to refine the groupings.

In [23]:
dt_ISPU.isna().sum()

parameter_pencemar_kritis     10
kategori                       0
periode_data                   0
bulan                          0
tanggal                        0
stasiun                        0
pm_sepuluh                   137
pm_duakomalima                38
sulfur_dioksida               43
karbon_monoksida              34
ozon                          31
nitrogen_dioksida             55
max                            0
dtype: int64

parameter_pencemar_kritis    10
kategori                      0
periode_data                  0
bulan                         0
tanggal                       0
stasiun                       0
pm_sepuluh                    0
pm_duakomalima                0
sulfur_dioksida               0
karbon_monoksida              0
ozon                          0
nitrogen_dioksida             0
max                           0
dtype: int64

In [25]:
pollutant_cols = ['pm_sepuluh', 'pm_duakomalima', 'sulfur_dioksida', 'karbon_monoksida', 'ozon', 'nitrogen_dioksida']

for index, row in dt_ISPU[dt_ISPU['parameter_pencemar_kritis'].isnull()].iterrows():
    max_col = row[pollutant_cols].idxmax()
    dt_ISPU.loc[index, 'parameter_pencemar_kritis'] = max_col

display(dt_ISPU.head())

,parameter_pencemar_kritis,kategori,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max
0,nitrogen_dioksida,SEDANG,202401,1,21,DKI3 Jagakarsa,51.000000,65.0,45.0,9.0,8.0,79.0,79.0
1,nitrogen_dioksida,SEDANG,202401,1,22,DKI3 Jagakarsa,27.000000,34.0,45.0,5.0,8.0,56.0,56.0
2,PM25,SEDANG,202401,1,23,DKI3 Jagakarsa,47.365422,52.0,46.0,6.0,9.0,51.0,52.0
3,PM25,SEDANG,202401,1,24,DKI3 Jagakarsa,46.000000,65.0,46.0,8.0,9.0,38.0,65.0
4,PM25,SEDANG,202401,1,25,DKI3 Jagakarsa,37.000000,55.0,47.0,7.0,11.0,28.0,55.0

In [26]:
dt_ISPU.isna().sum()

parameter_pencemar_kritis    0
kategori                     0
periode_data                 0
bulan                        0
tanggal                      0
stasiun                      0
pm_sepuluh                   0
pm_duakomalima               0
sulfur_dioksida              0
karbon_monoksida             0
ozon                         0
nitrogen_dioksida            0
max                          0
dtype: int64

,parameter_pencemar_kritis,kategori,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max
0,nitrogen_dioksida,SEDANG,2024,1,21,DKI3 Jagakarsa,51.000000,65.0,45.0,9.0,8.0,79.0,79.0
1,nitrogen_dioksida,SEDANG,2024,1,22,DKI3 Jagakarsa,27.000000,34.0,45.0,5.0,8.0,56.0,56.0
2,PM25,SEDANG,2024,1,23,DKI3 Jagakarsa,47.365422,52.0,46.0,6.0,9.0,51.0,52.0
3,PM25,SEDANG,2024,1,24,DKI3 Jagakarsa,46.000000,65.0,46.0,8.0,9.0,38.0,65.0
4,PM25,SEDANG,2024,1,25,DKI3 Jagakarsa,37.000000,55.0,47.0,7.0,11.0,28.0,55.0

In [42]:
dt_Volume_Sampah_Sungai = pd.read_excel('Volume Sampah Sungai.xlsx')
dt_Volume_Sampah_Sungai

,periode_data,wilayah,kecamatan,volume_sampah,total_sampah_residu,rata_rata
0,202401,KOTA ADM. JAKARTA PUSAT,Kemayoran,999.04,997.0,32.16
1,202401,KOTA ADM. JAKARTA PUSAT,Cempaka Putih,363.91,363.0,11.71
2,202401,KOTA ADM. JAKARTA PUSAT,Johar Baru,715.29,714.0,23.03
3,202401,KOTA ADM. JAKARTA PUSAT,Senen,500.13,498.0,16.06
4,202401,KOTA ADM. JAKARTA PUSAT,Sawah Besar,693.33,692.0,22.32
...,...,...,...,...,...,...
709,202505,Kota Adm. Jakarta Pusat,Sawah Besar,487.51,486.0,15.68
710,202505,Kota Adm. Jakarta Pusat,Menteng,330.63,328.0,10.58
711,202505,Kota Adm. Jakarta Pusat,Gambir,492.52,490.0,15.81
712,202505,Kota Adm. Jakarta Utara,Cilincing,883.19,873.0,28.16
713,202505,Kota Adm. Jakarta Utara,Kelapa Gading,610.92,607.9,19.61

In [43]:
dt_Volume_Sampah_Sungai.rename(columns={'rata_rata': 'rerata_harian'}, inplace=True)
display(dt_Volume_Sampah_Sungai.head())

,periode_data,wilayah,kecamatan,volume_sampah,total_sampah_residu,rerata_harian
0,202401,KOTA ADM. JAKARTA PUSAT,Kemayoran,999.04,997.0,32.16
1,202401,KOTA ADM. JAKARTA PUSAT,Cempaka Putih,363.91,363.0,11.71
2,202401,KOTA ADM. JAKARTA PUSAT,Johar Baru,715.29,714.0,23.03
3,202401,KOTA ADM. JAKARTA PUSAT,Senen,500.13,498.0,16.06
4,202401,KOTA ADM. JAKARTA PUSAT,Sawah Besar,693.33,692.0,22.32

In [44]:
dt_Volume_Sampah_Sungai.isna().sum()

periode_data           0
wilayah                0
kecamatan              0
volume_sampah          0
total_sampah_residu    0
rerata_harian          0
dtype: int64

DataFrame exported to dt_Volume_Sampah_Sungai_cleaned.csv

In [46]:
dt_RTH = pd.read_excel('RTH.xlsx')
dt_RTH

,periode_data,wilayah,kecamatan,kelurahan,nama_rth,alamat_rth,jenis_rth
0,2024,Kota Adm. Jakarta Pusat,Senen,Senen,Taman HKSN,"Jl. Pasar Senen, RW.3, Senen, Kec. Senen, Kota...",Taman
1,2024,Kota Adm. Jakarta Pusat,Taman Sari,Karang Anyar,Taman Maphar,"Jl. Karang Anyar No.22, RT.2/RW.2, Karang Anya...",Taman
2,2024,Kota Adm. Jakarta Pusat,Tanah Abang,Bendungan Hilir,JH Jl. Bendungan Hilir (bak tanaman),JH Jl. Bendungan Hilir (bak tanaman),Jalur Hijau
3,2024,Kota Adm. Jakarta Pusat,Tanah Abang,Bendungan Hilir,Taman Jembatan Tinggi Farmasi,Taman Jembatan Tinggi Farmasi,Jalur Hijau
4,2024,Kota Adm. Jakarta Pusat,Tanah Abang,Bendungan Hilir,Taman Penjernihan (segitiga) (dekat perumahan ...,Taman Penjernihan (segitiga) (dekat perumahan ...,Jalur Hijau
...,...,...,...,...,...,...,...
2540,2024,Kota Adm. Jakarta Utara,Koja,Rawabadak Selatan,RPTRA RASELA,"Jl. Alur Laut, RT.9/RW.5, South Rawabadak, Koj...",Taman
2541,2024,Kota Adm. Jakarta Utara,Koja,Rawabadak Selatan,TAMAN GOR RBS,"Jl. Alur Laut No.5A, RT.10/RW.4, Rawabadak Sel...",Taman
2542,2024,Kota Adm. Jakarta Utara,Koja,Rawabadak Selatan,TPU PLUMPANG,"Jl. Alur Laut Gg. k1 32, RT.9/RW.4, Rawabadak ...",TPU
2543,2024,Kota Adm. Jakarta Utara,Koja,Rawabadak Utara,JH Jl. Yos Sudarso Sisi Timur (Rawa Badak Utara),JH. Jl. Yos Sudarso Sisi Timur,Jalur Hijau
2544,2024,Kota Adm. Jakarta Utara,Koja,Rawabadak Utara,JH. Jl. Inspeksi Rawa Badak Utara/ Inspeksi Ka...,JH. Jl. Inspeksi Rawa Badak Utara/ Inspeksi Ka...,Jalur Hijau

In [47]:
dt_RTH.isna().sum()

periode_data      0
wilayah           0
kecamatan         0
kelurahan       482
nama_rth          0
alamat_rth        1
jenis_rth         0
dtype: int64

In [48]:
dt_RTH['kelurahan'] = dt_RTH.groupby('kecamatan')['kelurahan'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else None))
display(dt_RTH.isna().sum())

periode_data    0
wilayah         0
kecamatan       0
kelurahan       0
nama_rth        0
alamat_rth      1
jenis_rth       0
dtype: int64

/tmp/ipython-input-3684459736.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dt_RTH['alamat_rth'] = dt_RTH['alamat_rth'].fillna(method='ffill')

periode_data    0
wilayah         0
kecamatan       0
kelurahan       0
nama_rth        0
alamat_rth      0
jenis_rth       0
dtype: int64

In [50]:
dt_RTH.to_csv('dt_RTH_cleaned.csv', index=False)
print("DataFrame exported to dt_RTH_cleaned.csv")

DataFrame exported to dt_RTH_cleaned.csv